config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :books

	# login form
  get 'login', to: 'sessions#new'

  #check to see if we have a user, then set session[:user_id]
  post 'login',to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  post '/lookup', to: 'books#lookup'

  get '/', to: 'sessions#new'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :personal_books
	has_many :books, through: :personal_books

	validates :email, uniqueness: true

	validates :fname, presence: { message: "(First name) field cannot be blank" }
	validates :lname, presence: { message: "(Last name) field cannot be blank" }

	validates_confirmation_of :password
  

	validates :password, confirmation: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :send_to_login_unless_logged_in, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def change_password
    @page_title = "Changing account password"
    @user = current_user
    if request.post?

       @user.password = Digest::SHA1.hexdigest(params[:password][:password]) 
    if @user.save
        redirect_to :action => 'profile'
        flash[:status] = "Your password was changed. Next time you sign in use your new password."
      else
     flash[:status] = _('Your password not changed')
        render :action => "change_password"
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      puts "current user id is: #{params[:id]}"
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {}).permit(:fname, :lname, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Create a form to show/edit users -->
  <fieldset>
    <div class="well">
      <%= f.label :first_name %>
      <%= f.text_field :fname %>
    </div>  
  <br>
    <div class="well">
      <%= f.label :last_name %>
      <%= f.text_field :lname %>
    </div>
  <br>
    <div class="well">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <br>
    <div class="well">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
  <br>
    <div class="well">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>  
 
  </fieldset>


  
  <% if @current_user.nil? %>
    <%= f.submit 'Register', :class => 'btn btn-default' %>
    <%= link_to 'Cancel', login_path, class: 'btn btn-default' %>
  <% else %>
    <%= f.submit 'Update Registration', :class => 'btn btn-default' %>
    <%= link_to 'Back to My Library', user_path(session[:user_id]), class: 'btn btn-default' %>
  <% end %>
<% end %>

  

app/views/users/edit.html.erb
<div class="jumbotron">
  <div class="container">
		<h1>Editing User</h1>

		<%= render 'form', user: @user %>

	</div>
</div>

app/views/users/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="jumbotron">
  <div class="container">
    <h1>Users</h1>
      <table class="table table-bordered">
        <thead class="thead-inverse">
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th colspan="3">Actions</th>
          </tr>
        </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td class=center_text><%= user.id %></td>
            <td><%= user.fname %> 
              <%= user.lname %> 
            </td>
            <br>
            <td><%= user.email %></td>
            <td class=center_text><%= link_to 'Show', user %></td>
<!--         <td class=center_text><%#= link_to 'Edit', edit_user_path(user) %></td>
 -->         <td class=center_text><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <br>
<!-- Disabled link below to force only new user registration from Login screen (change if admin used) -->
<%#= link_to 'New User', new_user_path %>
    <div  class="btn btn-danger">
        <%= link_to 'Logout', logout_path, method: :delete, data: { confirm: 'Are you sure you want to logout?' } %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="jumbotron">
  <div class="container">
		<h1>New User</h1>

		<%= render 'form', user: @user %>
  </div>
</div>

app/views/users/show.html.erb
<!-- Show any notice returned from a previous action -->
<p id="notice"><%= notice %></p>
<!-- Display a single user -->
<span class="name">Showing User: <%= @user.fname %> <%=@user.lname %></span>
<span style="font-size: 15px; font-family: Helvetica"><%= link_to '(edit credentials)', edit_user_path(@user) %></span><br><br>


<span>Email: <%= @user.email %></span>


<table class="table table-striped table-hover">
  <thead>
    <tr> 
      <th>Title</th>
      <th>Author</th>
      <th>ISBN</th>
      <th>Cover</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
  	<% if @user.books.empty? %>
  		<tr>
  			<td>You have no books to show</td>
  			<td></td>
  			<td></td>
  			<td></td>
  			<td></td>
  		</tr>
  	<% else %>
	    <% @user.books.each do |book| %>
	      <tr>
	        <td><%= book.title %></td>
	        <td><%= book.author %></td>
	        <td><%= book.isbn %></td>
	        <td><%= image_tag book.book_cover_photo_sm %></td>
	        <td><%= link_to 'Show', book, class: 'page-link' %></td>
          <!-- <td><%#= link_to 'Remove', %> </td> -->
	      </tr>
	    <% end %>
	  <% end %>
  </tbody>
</table>