config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :books

	# login form
  get 'login', to: 'sessions#new'

  #check to see if we have a user, then set session[:user_id]
  post 'login',to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  post '/lookup', to: 'books#lookup'

  get '/', to: 'sessions#new'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GrpLibrary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar" style="background-color: #A6B0BF;">
      <div class="container-fluid" >
        <div class="navbar-header" style="color: #556171">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
    		
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% if session[:user_id] %>
            <ul class="nav navbar-nav">
          		<li>
                <%=	link_to 'My Library', user_path(session[:user_id]) %>
              </li>
          		<li>
                <%=	link_to 'Master Library', books_path %> 
              </li>
              <li>
          		  <%=	link_to 'Add a Book', new_book_path %>
          		</li>
              <%# if @current_user[:admin] %>
              <li>
          			<%= link_to 'Show Users', users_path %>
              </li>
              <%# end %>
          		<li>
          			<%= link_to 'Logout', logout_path, method: :delete, data: { confirm: 'Are you sure you want to logout?'}, style: "font-weight: bold;" %>
          		</li> 
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>